name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Change Directory and Check for Changes
        id: check_changes
        run: |
          cd src/module_A
          git diff --exit-code || echo "changes_detected=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Set Proceed Variable
        id: set_proceed
        run: |
          if [ -f src/module_A/changes_detected.txt ]; then
            echo "PROCEED_B=true" >> $GITHUB_ENV
          else
            echo "PROCEED_B=false" >> $GITHUB_ENV
          fi

      - name: Install all dependencies
        if: env.PROCEED_B == 'true'
        run: |
          cd src/module_A
          yarn

      - name: Build
        if: env.PROCEED_B == 'true'
        run: |
          cd src/module_A
          mkdir module_A_build

      - name: Copy Artifact
        if: env.PROCEED_B == 'true'
        run: |
          cd src/module_A
          cp README.md module_A_build

      - name: Push
        if: env.PROCEED_B == 'true'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: src/module_A/module_A_build
          TARGET_DIR: module_A_build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
