name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Change Directory and Check for Changes
        id: check_changes
        run: |
          cd src/module_B
          git diff --exit-code || echo "PROCEED_B=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Install all dependencies
        if: env.PROCEED_B == 'true'
        run: yarn

      - name: Build
        if: env.PROCEED_B == 'true'
        run: mkdir module_B_build

      - name: Copy Artifact
        if: env.PROCEED_B == 'true'
        run : cp README.md module_B_build

      - name: Push
        if: env.PROCEED_B == 'true'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: module_B_build
          TARGET_DIR: module_B_build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"