name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Change  Directory
        run: cd src/module_B

      - name: Install all dependencies
        run: yarn

      - name: Build
        run: mkdir module_B_build

      - name: Copy Artifact
        run : cp README.md module_B_build

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: module_B_build
          TARGET_DIR: module_B_build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"